# Binding
unbind C-b
set -g prefix C-a
bind C-a send-prefix
bind - split-window -v -c '#{pane_current_path}'
bind | split-window -h -c '#{pane_current_path}'
unbind '"'
unbind %
unbind r
bind r source-file ~/.config/tmux/tmux.conf
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
set -g base-index 1
setw -g pane-base-index 1
set -g mouse on
set -g default-terminal "tmux-256color"

# Plugins
set -g @plugin 'christoomey/vim-tmux-navigator'

set -g @vim_navigator_mapping_left "C-Left C-h"  # use C-h and C-Left
set -g @vim_navigator_mapping_right "C-Right C-l"
set -g @vim_navigator_mapping_up "C-k"
set -g @vim_navigator_mapping_down "C-j"
set -g @vim_navigator_mapping_prev ""

# UI Customizations
set -ogq @catppuccin_window_current_number ""
set -g @catppuccin_window_current_number_color "#bf616a"
set -g @catppuccin_window_current_text_color "#bf616a"
set -g @catppuccin_window_current_text "● #{b:pane_current_command}"
set -ogq @catppuccin_window_number ""
set -g @prefix_highlight_bg 'blue'
set-option -g status-position top
set -ogq @catppuccin_pane_status_enabled "yes"
set -ogq @catppuccin_pane_default_fill "number"
set -ogq @catppuccin_pane_number_position "left"
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "basic"
set -g @catppuccin_window_number_color "#d08770"
set -g @catppuccin_window_text_color "#d08770"
set -g @catppuccin_menu_selected_style "fg=#{@thm_surface_0},bg=#{@thm_yellow}"
set -g @catppuccin_window_text "  #{b:pane_current_command} "
set -ogq @catppuccin_window_number_position "left"
set -ogq @catppuccin_status_module_bg_color "#{@thm_surface_0}"
run '~/.tmux/plugins/catppuccin/tmux/catppuccin.tmux'
set -g status-left ""
set -g status-right ""

# TPM
set -g @plugin 'tmux-plugins/tpm'
run '~/.tmux/plugins/tpm/tpm'
